export const emojis = ['🎉', '🏄‍♂️', '🤩', '🙌', '🎊', '💯'];
export const encouragementTitles = [
  'Great Work!',
  'Well Done!',
  'You Rock!',
  'Nice One!',
  'Doing Great!',
  'Easy Peasy!',
];

export const encouragementMessages = [
  '"He who is not courageous enough to take risks will accomplish nothing in life."\n—Muhammad Ali',
  '"You can have anything you want if you want it badly enough. You can be anything you want to be, do anything you set out to accomplish if you hold to that desire with singleness of purpose.”\n—Abraham Lincoln',
  '"Here I am . . . wanting to accomplish something and completely forgetting it must all end—that there is such a thing as death.”\n—Leo Tolstoy',
  '"Knowing is not enough; we must apply. Willing is not enough; we must do."\n—Johann Wolfgang von Goethe',
  '"Do you want to know who you are? Don’t ask. Act! Action will delineate and define you.”\n—Thomas Jefferson',
  '"The path to success is to take massive, determined actions.”\n—Tony Robbins',
  '"Ambition is the path to success. Persistence is the vehicle you arrive in."\n—Bill Bradley',
  '"Ambition is enthusiasm with a purpose.”\n—Frank Tyger',
  '"A man’s worth is no greater than his ambitions.”\n—Marcus Aurelius',
  '"Believe it can be done. When you believe something can be done, really believe, your mind will find the ways to do it. Believing a solution paves the way to solution."\n—David Joseph Schwartz',
  '"Be brave to stand for what you believe in even if you stand alone.”\n—Roy T. Bennett',
  '"Believing in yourself is not for you; it\'s for every person who has touched your life in a significant way and for every person your life will touch the same way five minutes from now, or five centuries from now."\n—Jaye Miller',
  '"Clarity precedes success."\n—Robin Sharma',
  '"A lack of clarity could put the brakes on any journey to success.”\n—Steve Maraboli',
  '"Clarity affords focus.”\n—Thomas Leonard',
  '"The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy."\n—Martin Luther King, Jr.',
  '"The key to life is accepting challenges. Once someone stops doing this, he’s dead.”\n—Bette Davis',
  '"I don’t run away from a challenge because I am afraid. Instead, I run towards it because the only way to escape fear is to trample it beneath your foot.”\n—Nadia Comaneci',
  '"Once you have commitment, you need the discipline and hard work to get you there."\n—Haile Gebrselassie',
  '"Commitment is an act, not a word.”\n—Jean-Paul Sartre',
  '"Commitment is what transforms a promise into a reality.”\n—Abraham Lincoln',
  '"Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence."\n—Helen Keller',
  '"Self-confidence is the memory of success."\n—David Storey',
  '"Without self-confidence, we are as babes in the cradle.”\n—Virginia Woolf',
  '"Success is not final, failure is not fatal: it is the courage to continue that counts."\n—Winston Churchill',
  '"Courage is the most important of all the virtues because, without courage, you can’t practice any other virtue consistently.”\n—Maya Angelou',
  '"Courage is resistance to fear, mastery of fear—not absence of fear.”\n—Mark Twain',
  '"Failures are made only by those who fail to dare, not by those who dare to fail."\n—Lester B. Pearson',
  '"Far better is it to dare mighty things, to win glorious triumphs even though checkered by failure than to take rank with those poor spirits who neither enjoy much nor suffer much because they live in the grey twilight that knows neither victory nor defeat."\n—Theodore Roosevelt',
  '"Dare to dream, but even more importantly, dare to put action behind your dreams."\n—Josh Hinds',
  '"Failure will never overtake me if my determination to succeed is strong enough."\n—Og Mandino',
  '"A vow is fixed and unalterable determination to do a thing when such a determination is related to something noble which can only uplift the man who makes the resolve.”\n—Mahatma Gandhi',
  '"Desire is the key to motivation, but it’s the determination and commitment to an unrelenting pursuit of your goal—a commitment to excellence—that will enable you to attain the success you seek.”\n—Mario Andretti',
  '"You can do anything as long as you have the passion, the drive, the focus, and the support."\n—Sabrina Bryan',
  '"The road to success is not easy to navigate, but with hard work, drive, and passion, it\'s possible to achieve the American dream."\n—Tommy Hilfiger',
  '"Good business leaders create a vision, articulate the vision, passionately own the vision, and relentlessly drive it to completion."\n—Jack Welch',
  '"The mind is the limit. As long as the mind can envision the fact that you can do something, you can do it, as long as you really believe 100 percent."\n—Arnold Schwarzenegger',
  '"Envisioning the end is enough to put the means in motion.”\n—Dorthea Brande',
  '"I am an artist, and I have the ability and the free will to choose the way the world will envision me."\n—Lady Gaga',
  '"Excellence is not a skill, it\'s an attitude."\n—Ralph Marston',
  '"We are what we repeatedly do. Excellence, therefore, is not an act, but a habit.”\n—Aristotle',
  '"Excellence is a continuous process and not an accident.”\n—Abdul Kalam',
  '"It is during our darkest moments that we must focus to see the light."\n—Aristotle',
  '"I don’t care how much power, brilliance or energy you have, if you don’t harness it and focus it on a specific target, and hold it there you’re never going to accomplish as much as your ability warrants.”\n—Zig Ziglar',
  '"Your destiny is to fulfill those things upon which you focus most intently. So choose to keep your focus on that which is truly magnificent, beautiful, uplifting and joyful. Your life is always moving toward something.”\n—Ralph Marston',
  '"Forgiveness doesn\'t make the other person right; it makes you free."\n—Stormie Omartian',
  '"Forgiveness is the fragrance that the violet sheds on the heel that has crushed it.”\n—Mark Twain',
  '"The weak can never forgive. Forgiveness is the attribute of the strong.”\n—Mahatma Gandhi',
  '"Only those who have learned the power of sincere and selfless contribution experience life\'s deepest joy: true fulfillment."\n—Tony Robbins',
  '"If you devote yourself entirely to a noble pursuit, there is no way you cannot find beauty and fulfillment.”\n—Daniel Gillies',
  '"True happiness is a state of fulfillment.”\n—Ashish Sophat',
  '"Set your goals high, and don\'t stop \'til you get there."\n—Bo Jackson',
  '"Goals. There’s no telling what you can do when you get inspired by them. There’s no telling what you can do when you believe in them. And there’s no telling what will happen when you act upon them.”\n—Jim Rohn',
  '"If you set goals and go after them with all the determination you can muster, your gifts will take you places that will amaze you.”\n—Les Brown',
  '"Thankfulness is the beginning of gratitude. Gratitude is the completion of thankfulness. Thankfulness may consist merely of words. Gratitude is shown in acts.”\n—Henri Frederic Amiel',
  '"I would maintain that thanks are the highest form of thought and that gratitude is happiness doubled by wonder.”\n—Gilbert K. Chesterton',
  '"Gratitude is the healthiest of all human emotions. The more you express gratitude for what you have, the more likely you will have even more to express gratitude for.”\n—Zig Ziglar',
  '"Honesty is the first chapter in the book of wisdom."\n—Thomas Jefferson',
  '"Being honest may not get you a lot of friends but it’ll always get you the right ones.”\n—John Lennon',
  '"Honesty and transparency make you vulnerable. Be honest and transparent anyway.”\n—Mother Theresa',
  '"Hope is being able to see that there is light despite all of the darkness."\n—Desmond Tutu',
  '"We must accept finite disappointment but never lose infinite hope."\n—Martin Luther King, Jr.',
  '"What oxygen is to the lungs, such is hope to the meaning of life."\n—Emil Brunner',
  '"The true sign of intelligence is not knowledge but imagination."\n—Albert Einstein',
  '"Imagination will often carry us to worlds that never were. But without it, we go nowhere."\n—Carl Sagan',
  '"Laughter is timeless, imagination has no age and dreams are forever."\n—Walt Disney',
  '"What you do today can improve all your tomorrows."\n—Ralph Marston',
  '"Genius is one percent inspiration and ninety-nine percent perspiration."\n—Thomas A. Edison',
  '"Inspiration comes from within yourself. One has to be positive. When you\'re positive, good things happen."\n—Deep Roy',
  '"You can\'t wait for inspiration. You have to go after it with a club."\n—Jack London',
  '"Happiness lies in the joy of achievement and the thrill of creative effort."\n—Franklin D. Roosevelt',
  '"We cannot cure the world of sorrows, but we can choose to live in joy.”\n—Joseph Campbell',
  '"The soul’s joy lies in doing.”\n—Percy Bysshe Shelley',
  '"Kindness is the language which the deaf can hear and the blind can see."\n—Mark Twain',
  '"One who knows how to show and to accept kindness will be a friend better than any possession."\n—Sophocles',
  '"There’s no such thing as a small act of kindness. Every act creates a ripple with no logical end."\n—Scott Adams',
  '"An investment in knowledge pays the best interest."\n—Benjamin Franklin',
  '"Knowledge is power. Information is liberating. Education is the premise of progress, in every society, in every family."\n—Kofi Annan',
  '"True friendship can afford true knowledge. It does not depend on darkness and ignorance."\n—Henry David Thoreau',
  '"We have two ears and one mouth so that we can listen twice as much as we speak."\n—Epictetus',
  '"Listen with the intent to understand, not the intent to reply."\n—Stephen Covey',
  '"There is only one role for being a good talker—learn to listen."\n—Christopher Morley',
  '"With mindfulness, you can establish yourself in the present in order to touch the wonders of life that are available in that moment."\n—Thich Nhat Hanh',
  '"Mindfulness helps you go home to the present. And every time you go there and recognize a condition of happiness that you have, happiness comes."\n—Thich Nhat Hanh',
  '"Mindfulness is about love and loving life. When you cultivate this love, it gives you clarity and compassion for life, and your actions happen in accordance with that."\n—Jon Kabat-Zinn',
  '"To succeed in your mission, you must have single-minded devotion to your goal."\n—A. P. J. Abdul Kalam',
  '"Outstanding people have one thing in common: an absolute sense of mission."\n—Zig Ziglar',
  '"My measure of success is whether I\'m fulfilling my mission."\n—Robert Kiyosaki',
  '"Nurture your mind with great thoughts. To believe in the heroic makes heroes."\n—Benjamin Disraeli',
  '"The glory of gardening: hands in the dirt, head in the sun, heart with nature. To nurture a garden is to feed not just the body, but the soul."\n—Alfred Austin',
  '"If you nurture your mind, body, and spirit, your time will expand. You will gain a new perspective that will allow you to accomplish much more."\n—Brian Koslow',
  '"Failure is simply the opportunity to begin again, this time more intelligently."\n—Henry Ford',
  '"Success is where preparation and opportunity meet."\n—Bobby Unser',
  '"If opportunity doesn\'t knock, build a door."\n—Milton Berle',
  '"Outstanding people have one thing in common: an absolute sense of mission."\n—Zig Ziglar',
  '"Human beings are infinitely worth studying, especially the peculiarities that often go along with outstanding gifts."\n—Paul Johnson',
  '"The higher your energy level, the more efficient your body. The more efficient your body, the better you feel and the more you will use your talent to produce outstanding results."\n—Tony Robbins',
  '"Passion is one great force that unleashes creativity, because if you\'re passionate about something, then you\'re more willing to take risks."\n—Yo Yo Ma',
  '"Follow your passion, be prepared to work hard and sacrifice, and, above all, don\'t let anyone limit your dreams."\n—Donovan Bailey',
  '"Passion is energy. Feel the power that comes from focusing on what excites you."\n—Oprah Winfrey',
  '"Adopt the pace of nature: her secret is patience."\n—Ralph Waldo Emerson',
  '"The two most powerful warriors are patience and time."\n—Leo Tolstoy',
  '"Have patience. All things are difficult before they become easy."\n—Saadi',
  '"Perseverance is the hard work you do after you get tired of doing the hard work you already did."\n—Newt Gingrich',
  '"Perseverance is failing 19 times and succeeding the 20th."\n—Julie Andrews',
  '"No one succeeds without effort . . . Those who succeed owe their success to perseverance."\n—Ramana Maharshi',
  '"Practice does not make perfect. Only perfect practice makes perfect."\n—Vince Lombardi',
  '"Everything is practice."\n—Pele',
  '"An ounce of practice is worth more than tons of preaching."\n—Mahatma Gandhi',
  '"The key is not to prioritize what\'s on your schedule, but to schedule your priorities."\n—Stephen Covey',
  '"Pursuit of perfection is futile. Instead, I prioritize and often realize goals or tasks I\'ve been aiming for just aren\'t that important."\n—Aisha Tyler',
  '"The best we can do is prioritize our needs and make choices accordingly."\n—Janet Evanovich',
  '"A wise man can learn more from a foolish question than a fool can learn from a wise answer."\n—Bruce Lee',
  '"Question everything. Learn something. Answer nothing."\n—Euripides',
  '"By doubting we are led to question, by questioning we arrive at the truth."\n—Peter Abelard',
  '"By constant self-discipline and self-control you can develop greatness of character."\n—Grenville Kleiser',
  '"Emotional self-control is the result of hard work, not an inherent skill."\n—Travis Bradberry',
  '"Self-control means wanting to be effective at some random point in the infinite radiations of my spiritual existence."\n—Franz Kafka',
  '"It is possible to fly without motors, but not without knowledge and skill."\n—Wilbur Wright',
  '"When love and skill work together, expect a masterpiece."\n—John Ruskin',
  '"Learning how to learn is life\'s most important skill."\n—Tony Buzan',
  '"Share your smile with the world. It\'s a symbol of friendship and peace."\n—Christie Brinkley',
  '"Beauty is power; a smile is its sword."\n—John Ray',
  '"Nothing you wear is more important than your smile."\n—Connie Stevens',
  '"Failure will never overtake me if my determination to succeed is strong enough."\n—Og Mandino',
  '"In order to succeed, we must first believe that we can."\n—Nikos Kazantzakis',
  '"However difficult life may seem, there is always something you can do and succeed at."\n—Stephen Hawking',
  '"Think like a queen. A queen is not afraid to fail. Failure is another stepping stone to greatness."\n—Oprah Winfrey',
  '"When you think positive, good things happen."\n—Matt Kemp',
  '"Think in the morning. Act in the noon. Eat in the evening. Sleep in the night."\n—William Blake',
  '"Love all, trust a few, do wrong to none."\n—William Shakespeare',
  '"Trust yourself, you know more than you think you do."\n—Benjamin Spock',
  '"Trust in dreams, for in them is hidden the gate to eternity."\n—Khalil Gibran',
  '"One of the most beautiful qualities of true friendship is to understand and to be understood."\n—Lucius Annaeus Seneca',
  '"Mystery creates wonder, and wonder is the basis of man\'s desire to understand."\n—Neil Armstrong',
  '"If you can\'t explain it simply, you don\'t understand it well enough."\n—Albert Einstein',
  '"Try not to become a man of success, but rather try to become a man of value."\n—Albert Einstein',
  '"Price is what you pay. Value is what you get."\n—Warren Buffet',
  '"The value of life can be measured by how many times your soul has been deeply stirred."\n—Soichiro Honda',
  '"You were born to win, but to be a winner, you must plan to win, prepare to win, and expect to win."\n—Zig Ziglar',
  '"Self-praise is for losers. Be a winner. Stand for something. Always have class, and be humble."\n—John Madden',
  '"A winner never stops trying."\n—Tom Landry',
  '"The only true wisdom is in knowing you know nothing."\n—Socrates',
  '"Science is organized knowledge. Wisdom is organized life."\n—Immanuel Kant',
  '"Silence is true wisdom\'s best reply."\n—Euripides',
  '"Zeal will do more than knowledge."\n—William Hazlitt',
  '"Zeal without knowledge is fire without light."\n—Thomas Fuller',
  '"Zeal is a volcano, the peak of which the grass of indecisiveness does not grow."\n—Khalil Gibran',
];
